### ISSUE TITLE
ICE with `--emit asm`

### ISSUE THREAD

**Issue by dkm** [antoyo/rustc_codegen_gcc#40]
While adding support for rustc_cg_gcc in compiler explorer (see https://github.com/compiler-explorer/compiler-explorer/issues/2683 ), I run into an ICE because we are asking `rustc` to stop at asm.
It looks like it's not yet supported by your backend:

```
$ /bla/git/compiler-explorer/rustc-cg-gcc-master-20210626/bin/rustc -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so --sysroot /bla/git/compiler-explorer/rustc-cg-gcc-master-20210626/sysroot -C debuginfo=1 -o /tmp/output.s --emit asm --crate-type rlib --color=always /tmp/toto.rs
thread 'opt toto.3a1fbbbh-cgu.0' panicked at 'not implemented', src/back/write.rs:147:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (f586d79d1 2021-06-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=librustc_codegen_gcc.so -C panic=abort -C debuginfo=1 --crate-type rlib

query stack during panic:
end of query stack
thread '<unnamed>' panicked at '/rustc/f586d79d183d144e0cbf519e29247f36670e2076/compiler/rustc_codegen_ssa/src/back/write.rs:1508:21: worker thread panicked', compiler/rustc_middle/src/util/bug.rs:35:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (f586d79d1 2021-06-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=librustc_codegen_gcc.so -C panic=abort -C debuginfo=1 --crate-type rlib

query stack during panic:
end of query stack
thread 'rustc' panicked at '/rustc/f586d79d183d144e0cbf519e29247f36670e2076/compiler/rustc_codegen_ssa/src/back/write.rs:1824:17: panic during codegen/LLVM phase', compiler/rustc_middle/src/util/bug.rs:35:26
```
This is currently blocking for compiler-explorer, as compiler are expected to be able to output asm :)

**Comment by antoyo** [comment]
Thanks. I'll look at this ASAP.

**Comment by dkm** [comment]
Thanks!
